---> set the Role
 USE ROLE SYSADMIN ;
 
---> create the import_wh warehouse
 CREATE OR REPLACE WAREHOUSE IMPORT_WH      
  WAREHOUSE_TYPE = 'STANDARD'
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = FALSE
  INITIALLY_SUSPENDED = TRUE
  MAX_CLUSTER_COUNT = 1 ;
 
---> create the transform_wh warehouse
  CREATE OR REPLACE WAREHOUSE TRANSFORM_WH      
  WAREHOUSE_TYPE = 'STANDARD'
  WAREHOUSE_SIZE = 'MEDIUM'
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 300
  AUTO_RESUME = FALSE
  INITIALLY_SUSPENDED = TRUE
  MAX_CLUSTER_COUNT = 1 ;
  
---> create the reporting_wh warehouse
  CREATE OR REPLACE WAREHOUSE REPORTING_WH      
  WAREHOUSE_TYPE = 'STANDARD'
  WAREHOUSE_SIZE = 'SMALL'
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 900
  AUTO_RESUME = FALSE
  INITIALLY_SUSPENDED = TRUE
  MAX_CLUSTER_COUNT = 5;
   
---> set the Role
 USE ROLE SYSADMIN ;  
  
---> create the staging Database
CREATE DATABASE STAGING;

---> create the prod Database
CREATE DATABASE PROD;

---> create the Raw Schema
CREATE OR REPLACE SCHEMA STAGING.RAW
DATA_RETENTION_TIME_IN_DAYS = 3; 

---> create the Clean Schema
CREATE OR REPLACE SCHEMA STAGING.CLEAN
DATA_RETENTION_TIME_IN_DAYS = 3;; 

----> create the Reporting Schema
CREATE OR REPLACE SCHEMA PROD.REPORTING
DATA_RETENTION_TIME_IN_DAYS = 90;

---> Create roles
CREATE ROLE IMPORT_ROLE;
CREATE ROLE TRANSFORM_ROLE;
CREATE ROLE REPORT_ROLE;

---> Grant required privileges to Roles
GRANT USAGE ON WAREHOUSE IMPORT_WH TO ROLE IMPORT_ROLE;
GRANT USAGE ON DATABASE STAGING TO ROLE IMPORT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STAGING.RAW TO ROLE IMPORT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STAGING.CLEAN TO ROLE IMPORT_ROLE;
    
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;
--GRANT USGAE ON DATABASE STAGING TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STAGING.CLEAN TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PROD.REPORTING TO ROLE TRANSFORM_ROLE;
--GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PROD.REPORTING TO ROLE TRANSFORM_ROLE;

GRANT USAGE ON DATABASE PROD TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROD.REPORTING TO ROLE TRANSFORM_ROLE;

GRANT USAGE ON WAREHOUSE REPORT_WH TO ROLE REPORT_ROLE;
GRANT USAGE ON DATABASE PROD TO ROLE REPORT_ROLE;
GRANT USAGE ON SCHEMA PROD.REPORTING TO ROLE REPORT_ROLE;

---> Create Users
CREATE USER IMPORT_USER PASSWORD = 'IMP' 
DEFAULT_ROLE = IMPORT_ROLE MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = IMPORT_WH;

CREATE USER DATA_ENGINEER PASSWORD = 'DAT' 
DEFAULT_ROLE = TRANSFORM_ROLE MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = TRANSFORM_WH;

CREATE USER ETL_ADMIN PASSWORD = 'ETL' 
DEFAULT_ROLE = TRANSFORM_ROLE MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = TRANSFORM_WH;

CREATE USER POWER_USER PASSWORD = 'POW' 
DEFAULT_ROLE = (TRANSFORM_ROLE,REPORT_ROLE) MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = (TRANSFORM_WH,REPORT_WH);

CREATE USER BI_USER PASSWORD = 'BIU' 
DEFAULT_ROLE = REPORT_ROLE MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = REPORT_WH;

---> Create Users (Test Users) 
CREATE USER UserReporting PASSWORD = 'USR' 
DEFAULT_ROLE = REPORTING_ROLE MUST_CHANGE_PASSWORD = FALSE;

CREATE USER UserTransform PASSWORD = 'UST' 
DEFAULT_ROLE = TRANSFORM_ROLE MUST_CHANGE_PASSWORD = FALSE;

CREATE USER UserImport PASSWORD = 'USI' 
DEFAULT_ROLE = IMPORT_ROLEMUST_CHANGE_PASSWORD = FALSE;

---> Create Usage Monitors
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IMPORT_MONITOR WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR TRANSFORM_MONITOR WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR REPORTING_MONITOR WITH CREDIT_QUOTA = 100;

ALTER WAREHOUSE IMPORT_WH SET RESOURCE_MONITOR = IMPORT_MONITOR;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = TRANSFORM_MONITOR;
ALTER WAREHOUSE REPORTing_WH SET RESOURCE_MONITOR = REPORTING_MONITOR;


